class ServiceTitles {
  static const List<String> vinePhenologicalStates = [
    'A - Gomo de Inverno',
    'B - Gomo de Algodão',
    'C - Ponta Verde',
    'D - Saída de Folhas',
    'E - Folhas Livres',
    'F - Cachos Visíveis',
    'G - Cachos Separados',
    'H - Botões Florais Separados',
    'I - Floração',
    'J - Alimpa',
    'K - Bago de Ervilha',
    'L - Cacho Fechado',
    'M - Pintor',
    'N - Maturação',
    'O - Atempamento da Vara',
    'P - Queda de Folhas',
  ];

  static const Map<String, String> vinePhenologicalStateUuids = {
    'A - Gomo de Inverno': 'a_winter_bud',
    'B - Gomo de Algodão': 'b_woolly_bud',
    'C - Ponta Verde': 'c_bud_break',
    'D - Saída de Folhas': 'd_leaf_emergence',
    'E - Folhas Livres': 'e_leaves_separated',
    'F - Cachos Visíveis': 'f_inflorescences_visible',
    'G - Cachos Separados': 'g_inflorescences_separated',
    'H - Botões Florais Separados': 'h_flowers_separated',
    'I - Floração': 'i_bloom',
    'J - Alimpa': 'j_fruit_set',
    'K - Bago de Ervilha': 'k_berries_pea_size',
    'L - Cacho Fechado': 'l_berries_touching',
    'M - Pintor': 'm_veraison',
    'N - Maturação': 'n_maturity',
    'O - Atempamento da Vara': 'o_cane_maturation',
    'P - Queda de Folhas': 'p_leaf_fall',
  };

  static const List<String> vineVarieties = [
    'Alicante Bouschet',
    'Alicante Branco',
    'Alvarelhão',
    'Alvarelhão Branco',
    'Arinto (Pedernã)',
    'Aragonez (Tinta Roriz)',
    'Aramon',
    'Avesso',
    'Batoca',
    'Baga',
    'Barca',
    'Barreto',
    'Bragão',
    'Branco Especial',
    'Branco Guimarães',
    'Camarate',
    'Caramela',
    'Carrega Branco',
    'Carignan',
    'Cercial',
    'Chasselas',
    'Côdega de Larinho',
    'Diagalves',
    'Dona Branca',
    'Donzelinho Branco',
    'Donzelinho Tinto',
    'Engomada',
    'Espadeiro',
    'Fernão Pires (Maria Gomes)',
    'Folgasão',
    'Gouveio',
    'Gouveio Estimado',
    'Gouveio Real',
    'Gonçalo Pires',
    'Grand Noir',
    'Grangeal',
    'Jaen',
    'Jampal (Pinheira Branca)',
    'Lourela',
    'Malandra',
    'Malvasia Fina',
    'Malvasia Parda',
    'Malvasia Preta',
    'Malvasia Rei',
    'Marufo',
    'Melra',
    'Mondet',
    'Mourisco Branco',
    'Mourisco de Semente',
    'Nevoeira',
    'Patorra',
    'Pé Comprido',
    'Petit Bouschet',
    'Pinheira Branca',
    'Pinot Noir',
    'Praça',
    'Preto Martinho',
    'Rabigato',
    'Rabigato Franco',
    'Rabigato Moreno',
    'Rabo de Ovelha',
    'Ratinho',
    'Ricoca',
    'Roseira',
    'Rufete',
    'Samarrinho',
    'Sarigo',
    'Sercial (Esgana Cão)',
    'Síria (Roupeiro)',
    'Tália',
    'Tamarez',
    'Terrantez',
    'Tinta Aguiar',
    'Tinta Barroca',
    'Tinta Carvalha',
    'Tinta Fontes',
    'Tinta Francisca',
    'Tinta Lameira',
    'Tinta Martins',
    'Tinta Mesquita',
    'Tinta Penajóia',
    'Tinta Pereira',
    'Tinta Pomar',
    'Tinta Tabuaço',
    'Tinto Cão',
    'Tinto Sem Nome',
    'Touriga Branca',
    'Touriga Fêmea',
    'Touriga Franca',
    'Touriga Nacional',
    'Trincadeira',
    'Trigueira',
    'Valdosa',
    'Valente',
    'Varejoa',
    'Verdial Branco',
    'Viosinho',
    'Vital',
  ];
}