// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/observation.dart';
import 'models/observation_image.dart';
import 'models/service.dart';
import 'models/user.dart';
import 'models/user_group.dart';
import 'models/user_service.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 9006605549728188499),
    name: 'Observation',
    lastPropertyId: const obx_int.IdUid(15, 8062569599956811509),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 592933627446317223),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6119514926636738280),
        name: 'remoteUuid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8669565356805592892),
        name: 'userUuid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7231336898324293482),
        name: 'serviceUuid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1325297212617541033),
        name: 'serviceSlug',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4628217285840841956),
        name: 'userGroupUuid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4146901008257659222),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8651091140294875730),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1119943605515751025),
        name: 'latitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 3989615739808879019),
        name: 'longitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 8914398031741599250),
        name: 'geocode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 6410837488077903880),
        name: 'isPublic',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 8898540565575833086),
        name: 'syncStatus',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 6482525189417705771),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 8062569599956811509),
        name: 'titleUuid',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7961293682945556047),
    name: 'ObservationImage',
    lastPropertyId: const obx_int.IdUid(5, 6106950238021785835),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2846862663971755629),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8046626858691037428),
        name: 'observationId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3587355220535725351),
        name: 'localPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1093883340864152611),
        name: 'remoteUuid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6106950238021785835),
        name: 'uploaded',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 9208865971335527599),
    name: 'Service',
    lastPropertyId: const obx_int.IdUid(5, 6630388761815687283),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1202683008449321671),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3433598906019206134),
        name: 'uuid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1562397292269550861),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3573799326760598142),
        name: 'slug',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6630388761815687283),
        name: 'open',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 1015276675855684759),
    name: 'User',
    lastPropertyId: const obx_int.IdUid(8, 4904567731569992427),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7054696292751708622),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4083709443921396169),
        name: 'uuid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8207720977025740372),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8780067671223515074),
        name: 'username',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8616704706147170638),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4368216298871245822),
        name: 'avatarLocalPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 127191224380824742),
        name: 'nrObs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4904567731569992427),
        name: 'avatarUrl',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 7923309824319556000),
    name: 'UserGroup',
    lastPropertyId: const obx_int.IdUid(4, 1433255599517973214),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3043519284033146906),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 339022399370010646),
        name: 'uuid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6964751534628625629),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1433255599517973214),
        name: 'userUuid',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 6627519481000307131),
    name: 'UserService',
    lastPropertyId: const obx_int.IdUid(4, 3250643862018770118),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8099989617123264886),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1233113385827092680),
        name: 'userUuid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2949818519759319294),
        name: 'serviceUuid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3250643862018770118),
        name: 'subscribed',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(6, 6627519481000307131),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Observation: obx_int.EntityDefinition<Observation>(
      model: _entities[0],
      toOneRelations: (Observation object) => [],
      toManyRelations: (Observation object) => {},
      getId: (Observation object) => object.id,
      setId: (Observation object, int id) {
        object.id = id;
      },
      objectToFB: (Observation object, fb.Builder fbb) {
        final remoteUuidOffset = fbb.writeString(object.remoteUuid);
        final userUuidOffset = fbb.writeString(object.userUuid);
        final serviceUuidOffset = fbb.writeString(object.serviceUuid);
        final serviceSlugOffset = fbb.writeString(object.serviceSlug);
        final userGroupUuidOffset = fbb.writeString(object.userGroupUuid);
        final titleOffset = fbb.writeString(object.title);
        final descriptionOffset = fbb.writeString(object.description);
        final geocodeOffset = fbb.writeString(object.geocode);
        final syncStatusOffset = fbb.writeString(object.syncStatus);
        final titleUuidOffset = fbb.writeString(object.titleUuid);
        fbb.startTable(16);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, remoteUuidOffset);
        fbb.addOffset(2, userUuidOffset);
        fbb.addOffset(3, serviceUuidOffset);
        fbb.addOffset(4, serviceSlugOffset);
        fbb.addOffset(5, userGroupUuidOffset);
        fbb.addOffset(6, titleOffset);
        fbb.addOffset(7, descriptionOffset);
        fbb.addFloat64(8, object.latitude);
        fbb.addFloat64(9, object.longitude);
        fbb.addOffset(10, geocodeOffset);
        fbb.addBool(11, object.isPublic);
        fbb.addOffset(12, syncStatusOffset);
        fbb.addInt64(13, object.createdAt.millisecondsSinceEpoch);
        fbb.addOffset(14, titleUuidOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final remoteUuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final userUuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final serviceUuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final serviceSlugParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final userGroupUuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final titleUuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 32, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final latitudeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final longitudeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final geocodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final isPublicParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          26,
          false,
        );
        final syncStatusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 28, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 30, 0),
        );
        final object = Observation(
          remoteUuid: remoteUuidParam,
          userUuid: userUuidParam,
          serviceUuid: serviceUuidParam,
          serviceSlug: serviceSlugParam,
          userGroupUuid: userGroupUuidParam,
          title: titleParam,
          titleUuid: titleUuidParam,
          description: descriptionParam,
          latitude: latitudeParam,
          longitude: longitudeParam,
          geocode: geocodeParam,
          isPublic: isPublicParam,
          syncStatus: syncStatusParam,
          createdAt: createdAtParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    ObservationImage: obx_int.EntityDefinition<ObservationImage>(
      model: _entities[1],
      toOneRelations: (ObservationImage object) => [],
      toManyRelations: (ObservationImage object) => {},
      getId: (ObservationImage object) => object.id,
      setId: (ObservationImage object, int id) {
        object.id = id;
      },
      objectToFB: (ObservationImage object, fb.Builder fbb) {
        final localPathOffset = fbb.writeString(object.localPath);
        final remoteUuidOffset = fbb.writeString(object.remoteUuid);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.observationId);
        fbb.addOffset(2, localPathOffset);
        fbb.addOffset(3, remoteUuidOffset);
        fbb.addBool(4, object.uploaded);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final observationIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final localPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final remoteUuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final uploadedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          12,
          false,
        );
        final object = ObservationImage(
          observationId: observationIdParam,
          localPath: localPathParam,
          remoteUuid: remoteUuidParam,
          uploaded: uploadedParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    Service: obx_int.EntityDefinition<Service>(
      model: _entities[2],
      toOneRelations: (Service object) => [],
      toManyRelations: (Service object) => {},
      getId: (Service object) => object.id,
      setId: (Service object, int id) {
        object.id = id;
      },
      objectToFB: (Service object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final nameOffset = fbb.writeString(object.name);
        final slugOffset = fbb.writeString(object.slug);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, slugOffset);
        fbb.addBool(4, object.open);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final slugParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final openParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          12,
          false,
        );
        final object = Service(
          uuid: uuidParam,
          name: nameParam,
          slug: slugParam,
          open: openParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    User: obx_int.EntityDefinition<User>(
      model: _entities[3],
      toOneRelations: (User object) => [],
      toManyRelations: (User object) => {},
      getId: (User object) => object.id,
      setId: (User object, int id) {
        object.id = id;
      },
      objectToFB: (User object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final nameOffset = fbb.writeString(object.name);
        final usernameOffset = fbb.writeString(object.username);
        final emailOffset = fbb.writeString(object.email);
        final avatarLocalPathOffset = fbb.writeString(object.avatarLocalPath);
        final avatarUrlOffset = fbb.writeString(object.avatarUrl);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, usernameOffset);
        fbb.addOffset(4, emailOffset);
        fbb.addOffset(5, avatarLocalPathOffset);
        fbb.addInt64(6, object.nrObs);
        fbb.addOffset(7, avatarUrlOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final usernameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final avatarLocalPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final avatarUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final nrObsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final object = User(
          uuid: uuidParam,
          name: nameParam,
          username: usernameParam,
          email: emailParam,
          avatarLocalPath: avatarLocalPathParam,
          avatarUrl: avatarUrlParam,
          nrObs: nrObsParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    UserGroup: obx_int.EntityDefinition<UserGroup>(
      model: _entities[4],
      toOneRelations: (UserGroup object) => [],
      toManyRelations: (UserGroup object) => {},
      getId: (UserGroup object) => object.id,
      setId: (UserGroup object, int id) {
        object.id = id;
      },
      objectToFB: (UserGroup object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final nameOffset = fbb.writeString(object.name);
        final userUuidOffset = fbb.writeString(object.userUuid);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, userUuidOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final userUuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object = UserGroup(
          userUuid: userUuidParam,
          uuid: uuidParam,
          name: nameParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    UserService: obx_int.EntityDefinition<UserService>(
      model: _entities[5],
      toOneRelations: (UserService object) => [],
      toManyRelations: (UserService object) => {},
      getId: (UserService object) => object.id,
      setId: (UserService object, int id) {
        object.id = id;
      },
      objectToFB: (UserService object, fb.Builder fbb) {
        final userUuidOffset = fbb.writeString(object.userUuid);
        final serviceUuidOffset = fbb.writeString(object.serviceUuid);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, userUuidOffset);
        fbb.addOffset(2, serviceUuidOffset);
        fbb.addBool(3, object.subscribed);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final userUuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final serviceUuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final subscribedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final object = UserService(
          userUuid: userUuidParam,
          serviceUuid: serviceUuidParam,
          subscribed: subscribedParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Observation] entity fields to define ObjectBox queries.
class Observation_ {
  /// See [Observation.id].
  static final id = obx.QueryIntegerProperty<Observation>(
    _entities[0].properties[0],
  );

  /// See [Observation.remoteUuid].
  static final remoteUuid = obx.QueryStringProperty<Observation>(
    _entities[0].properties[1],
  );

  /// See [Observation.userUuid].
  static final userUuid = obx.QueryStringProperty<Observation>(
    _entities[0].properties[2],
  );

  /// See [Observation.serviceUuid].
  static final serviceUuid = obx.QueryStringProperty<Observation>(
    _entities[0].properties[3],
  );

  /// See [Observation.serviceSlug].
  static final serviceSlug = obx.QueryStringProperty<Observation>(
    _entities[0].properties[4],
  );

  /// See [Observation.userGroupUuid].
  static final userGroupUuid = obx.QueryStringProperty<Observation>(
    _entities[0].properties[5],
  );

  /// See [Observation.title].
  static final title = obx.QueryStringProperty<Observation>(
    _entities[0].properties[6],
  );

  /// See [Observation.description].
  static final description = obx.QueryStringProperty<Observation>(
    _entities[0].properties[7],
  );

  /// See [Observation.latitude].
  static final latitude = obx.QueryDoubleProperty<Observation>(
    _entities[0].properties[8],
  );

  /// See [Observation.longitude].
  static final longitude = obx.QueryDoubleProperty<Observation>(
    _entities[0].properties[9],
  );

  /// See [Observation.geocode].
  static final geocode = obx.QueryStringProperty<Observation>(
    _entities[0].properties[10],
  );

  /// See [Observation.isPublic].
  static final isPublic = obx.QueryBooleanProperty<Observation>(
    _entities[0].properties[11],
  );

  /// See [Observation.syncStatus].
  static final syncStatus = obx.QueryStringProperty<Observation>(
    _entities[0].properties[12],
  );

  /// See [Observation.createdAt].
  static final createdAt = obx.QueryDateProperty<Observation>(
    _entities[0].properties[13],
  );

  /// See [Observation.titleUuid].
  static final titleUuid = obx.QueryStringProperty<Observation>(
    _entities[0].properties[14],
  );
}

/// [ObservationImage] entity fields to define ObjectBox queries.
class ObservationImage_ {
  /// See [ObservationImage.id].
  static final id = obx.QueryIntegerProperty<ObservationImage>(
    _entities[1].properties[0],
  );

  /// See [ObservationImage.observationId].
  static final observationId = obx.QueryIntegerProperty<ObservationImage>(
    _entities[1].properties[1],
  );

  /// See [ObservationImage.localPath].
  static final localPath = obx.QueryStringProperty<ObservationImage>(
    _entities[1].properties[2],
  );

  /// See [ObservationImage.remoteUuid].
  static final remoteUuid = obx.QueryStringProperty<ObservationImage>(
    _entities[1].properties[3],
  );

  /// See [ObservationImage.uploaded].
  static final uploaded = obx.QueryBooleanProperty<ObservationImage>(
    _entities[1].properties[4],
  );
}

/// [Service] entity fields to define ObjectBox queries.
class Service_ {
  /// See [Service.id].
  static final id = obx.QueryIntegerProperty<Service>(
    _entities[2].properties[0],
  );

  /// See [Service.uuid].
  static final uuid = obx.QueryStringProperty<Service>(
    _entities[2].properties[1],
  );

  /// See [Service.name].
  static final name = obx.QueryStringProperty<Service>(
    _entities[2].properties[2],
  );

  /// See [Service.slug].
  static final slug = obx.QueryStringProperty<Service>(
    _entities[2].properties[3],
  );

  /// See [Service.open].
  static final open = obx.QueryBooleanProperty<Service>(
    _entities[2].properties[4],
  );
}

/// [User] entity fields to define ObjectBox queries.
class User_ {
  /// See [User.id].
  static final id = obx.QueryIntegerProperty<User>(_entities[3].properties[0]);

  /// See [User.uuid].
  static final uuid = obx.QueryStringProperty<User>(_entities[3].properties[1]);

  /// See [User.name].
  static final name = obx.QueryStringProperty<User>(_entities[3].properties[2]);

  /// See [User.username].
  static final username = obx.QueryStringProperty<User>(
    _entities[3].properties[3],
  );

  /// See [User.email].
  static final email = obx.QueryStringProperty<User>(
    _entities[3].properties[4],
  );

  /// See [User.avatarLocalPath].
  static final avatarLocalPath = obx.QueryStringProperty<User>(
    _entities[3].properties[5],
  );

  /// See [User.nrObs].
  static final nrObs = obx.QueryIntegerProperty<User>(
    _entities[3].properties[6],
  );

  /// See [User.avatarUrl].
  static final avatarUrl = obx.QueryStringProperty<User>(
    _entities[3].properties[7],
  );
}

/// [UserGroup] entity fields to define ObjectBox queries.
class UserGroup_ {
  /// See [UserGroup.id].
  static final id = obx.QueryIntegerProperty<UserGroup>(
    _entities[4].properties[0],
  );

  /// See [UserGroup.uuid].
  static final uuid = obx.QueryStringProperty<UserGroup>(
    _entities[4].properties[1],
  );

  /// See [UserGroup.name].
  static final name = obx.QueryStringProperty<UserGroup>(
    _entities[4].properties[2],
  );

  /// See [UserGroup.userUuid].
  static final userUuid = obx.QueryStringProperty<UserGroup>(
    _entities[4].properties[3],
  );
}

/// [UserService] entity fields to define ObjectBox queries.
class UserService_ {
  /// See [UserService.id].
  static final id = obx.QueryIntegerProperty<UserService>(
    _entities[5].properties[0],
  );

  /// See [UserService.userUuid].
  static final userUuid = obx.QueryStringProperty<UserService>(
    _entities[5].properties[1],
  );

  /// See [UserService.serviceUuid].
  static final serviceUuid = obx.QueryStringProperty<UserService>(
    _entities[5].properties[2],
  );

  /// See [UserService.subscribed].
  static final subscribed = obx.QueryBooleanProperty<UserService>(
    _entities[5].properties[3],
  );
}
